-- Example output of spritesheet.py

local Video = require(script.Parent)

local EncounterExclamationPoint = {}

local EncounterExclamationPointSheet0 = "rbxassetid://17248828907"
local EncounterExclamationPointSheet1 = "rbxassetid://17248828778"
local EncounterExclamationPointSheet2 = "rbxassetid://17248828599"
local EncounterExclamationPointSheet3 = "rbxassetid://17248828447"
local EncounterExclamationPointSheet4 = "rbxassetid://17248828349"

function EncounterExclamationPoint.new()
	local EncounterExclamationPoint = Video.new(Vector2.new(256, 256))

	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_1", Vector2.new(0, 0), EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_10", Vector2.new(256, 0),  EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_11", Vector2.new(512, 0), EncounterExclamationPointSheet0)
    Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_12", Vector2.new(768, 0), EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_13", Vector2.new(0, 256), EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_14", Vector2.new(256, 256), EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_15", Vector2.new(512, 256), EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_16", Vector2.new(768, 256), EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_17", Vector2.new(0, 512), EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_18", Vector2.new(256, 512), EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_19", Vector2.new(512, 512), EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_2", Vector2.new(768, 512),EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_20", Vector2.new(0, 768), EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_21", Vector2.new(256, 768), EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_22", Vector2.new(512, 768), EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_23", Vector2.new(768, 768), EncounterExclamationPointSheet0)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_24", Vector2.new(0, 0), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_25", Vector2.new(256, 0), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_26", Vector2.new(512, 0), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_27", Vector2.new(768, 0), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_28", Vector2.new(0, 256), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_29", Vector2.new(256, 256), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_3", Vector2.new(512, 256),EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_30", Vector2.new(768, 256), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_31", Vector2.new(0, 512), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_32", Vector2.new(256, 512), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_33", Vector2.new(512, 512), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_34", Vector2.new(768, 512), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_35", Vector2.new(0, 768), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_36", Vector2.new(256, 768), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_37", Vector2.new(512, 768), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_38", Vector2.new(768, 768), EncounterExclamationPointSheet1)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_39", Vector2.new(0, 0), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_4", Vector2.new(256, 0), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_40", Vector2.new(512, 0), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_41", Vector2.new(768, 0), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_42", Vector2.new(0, 256), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_43", Vector2.new(256, 256), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_44", Vector2.new(512, 256), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_45", Vector2.new(768, 256), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_46", Vector2.new(0, 512), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_47", Vector2.new(256, 512), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_48", Vector2.new(512, 512), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_49", Vector2.new(768, 512), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_5", Vector2.new(0, 768), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_50", Vector2.new(256, 768), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_51", Vector2.new(512, 768), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_52", Vector2.new(768, 768), EncounterExclamationPointSheet2)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_53", Vector2.new(0, 0), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_54", Vector2.new(256, 0), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_55", Vector2.new(512, 0), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_56", Vector2.new(768, 0), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_57", Vector2.new(0, 256), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_58", Vector2.new(256, 256), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_59", Vector2.new(512, 256), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_6", Vector2.new(768, 256),EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_60", Vector2.new(0, 512), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_61", Vector2.new(256, 512), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_62", Vector2.new(512, 512), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_63", Vector2.new(768, 512), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_64", Vector2.new(0, 768), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_65", Vector2.new(256, 768), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_66", Vector2.new(512, 768), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_67", Vector2.new(768, 768), EncounterExclamationPointSheet3)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_68", Vector2.new(0, 0), EncounterExclamationPointSheet4)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_69", Vector2.new(256, 0), EncounterExclamationPointSheet4)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_7", Vector2.new(512, 0), EncounterExclamationPointSheet4)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_70", Vector2.new(768, 0), EncounterExclamationPointSheet4)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_71", Vector2.new(0, 256), EncounterExclamationPointSheet4)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_72", Vector2.new(256, 256), EncounterExclamationPointSheet4)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_8", Vector2.new(512, 256),EncounterExclamationPointSheet4)
	Video.addFrame(EncounterExclamationPoint, "encounter_EncounterExclamationPoint_point_frame_9", Vector2.new(768, 256),EncounterExclamationPointSheet4)
	return EncounterExclamationPoint
end

return EncounterExclamationPoint
